[package]
name = "hfq_rs"
version = "0.0.1"
authors = ["Nishizacky"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { version = "0.25.1", features = ["lazy"] }
chrono = "0.4.30"
regex = "1.10.0"
rand = "0.8.5"
tokio = "1.35.0"
plotters="0.3.3"

[lib]
name = "hfq_rs"
crate-type = ["rlib","dylib"]
